dist: xenial
language: python

env:
  global:
    - PYTEST_ADDOPTS="-vv --cov --cov-report=xml"

stages:
  - name: test
    if: tag IS NOT present
  - name: release
    if: tag IS present

jobs:
  include:
    - os: windows
      language: shell
      env:
        - PATH=/c/Python38:/c/Python38/Scripts:$PATH
        - TOXENV=py38-coverage
      before_install:
        - choco install --no-progress python

    - os: osx
      osx_image: xcode10.2
      language: generic
      env: TOXENV=py37-coverage
      before_install:
        - ln -sfn "$(which python3)" /usr/local/bin/python
        - python -V
        - test $(python -c 'import sys; print("%d%d" % sys.version_info[0:2])') = 37

    - python: '2.7'
      env: TOXENV=py27-coverage
    - python: '3.4'
      env: TOXENV=py34-coverage
    - python: '3.5'
      env: TOXENV=py35-coverage
    - python: '3.6'
      env: TOXENV=py36-coverage
    - python: '3.7'
      env: TOXENV=py37-coverage
    - python: '3.8-dev'
      env: TOXENV=py38-coverage
    - python: 'pypy'
      env: TOXENV=pypy-coverage
    - python: 'pypy3'
      env: TOXENV=pypy3-coverage

    - python: '3.7'
      env: TOXENV=checkqa

    - stage: release
      script: skip
      install: skip
      after_success: true
      env:
      deploy:
        provider: pypi
        distributions: sdist bdist_wheel
        user: __token__
        password:
          secure: "gucshhwm48kCIWThlbqhE08HIdjHgZtOSBKDgxAS57mR+lDVVtX6tdoitYSNPugMuYCgA6WEtg3Ikd+clbUTv7lfs5gDBlHrgjRO6qDDJ1PWgcxhSJ+nctaOEhHN5CVXg7wsGYtavM99sJYsu3RZGPg0IGjT/Z1792gNCBIMmE/j4r2G6tQZ+FdHCVtT2YQ74bLFV1BrnZa579NTuSQ8QhFz8Pccd0XpSSzQ/T1xRUMr5FZj9ecg4CRob+dKIIZWfExeJN0rv1UgqR6/D3qO7hoDwKYCNikv8VuB04LB6c+6Pc9yAGjSieGTKl7rGc6jQCvevCvSjitITGlhbjUnIT9br8B7cywUiZ+3rRJ7W2phxlHbGKxldA8tQhyYPqjr0EfO2gYlRoSikPNY6m9iM9igP67osnyih52aUjssoX9PNwuzwwEume2cnKRb3oyzWoqboH2dj/eJFaP1hi9w+56WDh/+7jRpEiBQ3G8Ph45BvxvwtPikedTZgShTqEYQLp1JEZFdQZD35dCMAnmVAogbQjLgGTjQ1T1pnK1tsu1Hu+QOphTDVW7MyRiQ5dj6E0/Hah0l6tjlsFT/QfjjMO6f1bBzTktBlfRheHPrPervulHVwhZavcNJ4vE6mdObSWBaGHaI8imNMnSautlbn/yHo+UxfVnjRGcM5zpLAMc="
        on:
          tags: true
          repo: pdbpp/fancycompleter

install:
  - pip install tox==3.12.1
  # NOTE: need to upgrade virtualenv to allow "Direct url requirement" with
  # installation in tox.
  - pip install virtualenv==16.6.0

script:
  - tox

after_script:
  - |
    if [[ "${TOXENV%-coverage}" != "$TOXENV" ]]; then
      curl --version
      curl -S -L --connect-timeout 5 --retry 6 -s https://codecov.io/bash > codecov.sh
      bash codecov.sh -Z -X fix -f coverage.xml -n $TOXENV -F "${TRAVIS_OS_NAME}"
    fi

# Only master and releases.  PRs are used otherwise.
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
